
disabled-items:
  - SPAWNER
  - SPAWNER_EGGS

messages:
  cannot_afford: "&#9e9e9eYou cannot afford this &#16bf6d(&#9e9e9e$&#16bf6d${total}&#16bf6d&#9e9e9e)&#9e9e9e."
  order_full: "&#9e9e9eOrder is &#16bf6dfull&#9e9e9e."
  received_actionbar: "&#16bf6d{player} &#9e9e9ehas delivered you &#16bf6d{amount} {item}&#9e9e9e!"


search-sign:
  lines:
    - ""
    - "↑↑↑↑↑↑↑↑↑↑↑↑↑↑"
    - "Search"
    - ""

  input-line: 1

amount-sign:
  lines:
    - ""
    - "↑↑↑↑↑↑↑↑↑↑↑↑↑↑"
    - "Amount"
    - ""
  input-line: 1

price-sign:
  lines:
    - ""
    - "↑↑↑↑↑↑↑↑↑↑↑↑↑↑"
    - "Price"
    - ""
  input-line: 1


sounds:
  click:
    sound: UI_BUTTON_CLICK
    volume: 1.0
    pitch: 1.0
  page:
    sound: ITEM_BOOK_PAGE_TURN
    volume: 1.0
    pitch: 1.1
  refresh:
    sound: UI_TOAST_IN
    volume: 1.0
    pitch: 1.0
  open:
    sound: BLOCK_CHEST_OPEN
    volume: 0.7
    pitch: 1.0
  confirm:
    sound: ENTITY_EXPERIENCE_ORB_PICKUP
    volume: 1.0
    pitch: 1.2
  cancel:
    sound: BLOCK_NOTE_BLOCK_BASS
    volume: 1.0
    pitch: 0.8
  received:
    sound: ENTITY_PLAYER_LEVELUP
    volume: 1.0
    pitch: 1.2

sort-names:
  MOST_PAID: "Most Paid"
  MOST_DELIVERED: "Most Delivered"
  RECENTLY_LISTED: "Recently Listed"
  MOST_MONEY_PER_ITEM: "Most Money Per Item"

gui:

  orders:
    title: "&#444444ᴏʀᴅᴇʀѕ"
    rows: 6
    format:
      selected_prefix: "&#34ee80• "
      unselected_prefix: "&f• "
    items:
      prev:
        slot: 45
        material: ARROW
        displayname: "&#34ee80ʙᴀᴄᴋ"
        lore:
          - "&fClick to go to the previous page"
      sort:
        slot: 47
        material: CAULDRON
        displayname: "&#34ee80ѕᴏʀᴛ"
        lore: []
      filter:
        slot: 48
        material: HOPPER
        displayname: "&#34ee80ꜰɪʟᴛᴇʀ"
        lore: []
      refresh:
        slot: 49
        material: MAP
        displayname: "&#34ee80ʀᴇꜰʀᴇѕʜ"
        lore:
          - "&fClick to refresh"
      search:
        slot: 50
        material: OAK_SIGN
        displayname: "&#34ee80ѕᴇᴀʀᴄʜ"
        lore:
          - "&fClick to search"
      your:
        slot: 51
        material: CHEST
        displayname: "&#34ee80ʏᴏᴜʀ ᴏʀᴅᴇʀѕ"
        lore:
          - "&fClick to view your orders"
      next:
        slot: 53
        material: ARROW
        displayname: "&#34ee80ɴᴇхᴛ"
        lore:
          - "&fClick to go to the next page"

      order-item:
        displayname: "&#34ee80{player}'s Order"
        lore:
          - "&f{item}"
          - "&#34ee80${price_each} &feach"
          - ""
          - "&#7E7E29{delivered}/&#008D4C{requested} &#858585Delivered"
          - "&#7E7E29${paid}/&#008D4C${total} &#858585paid"
          - ""
          - "&fClick to deliver &#34ee80{player} &f{item}"


  your:
    title: "&#444444ᴏʀᴅᴇʀѕ -> Your Orders"
    rows: 3
    items:
      order-item:
        displayname: "&#34ee80{player}'s Order"
        lore:
          - "&#34ee80{requested} &f{item}"
          - "&#34ee80${price_each} &feach"
          - ""
          - "&#7E7E29{delivered}/&#008D4C{requested} &#858585Delivered"
          - "&#7E7E29${paid}/&#008D4C${total} &#858585Paid"
      new:
        material: MAP
        displayname: "&#34ee80New Order"
        lore:
          - "&fClick to create new order"

  new:
    title: "&#444444ᴏʀᴅᴇʀ -> New Order"
    rows: 3
    filler:
      enabled: true
      slots: "1,9,10"
      material: GRAY_STAINED_GLASS_PANE
      displayname: "&7 "
    items:
      cancel:
        material: RED_STAINED_GLASS_PANE
        displayname: "&#FF3B3Bᴄᴀɴᴄᴇʟ"
        lore:
          - "&fClick to return"
      item:
        material: STONE
        displayname: "&#34ee80ɪᴛᴇᴍ"
        lore:
          - "&fClick to choose item"
          - "&7({item})"
      amount:
        material: CHEST
        displayname: "&#34ee80ᴀᴍᴏᴜɴᴛ"
        lore:
          - "&fClick to type number of items"
          - "&7({amount})"
      price:
        material: EMERALD
        displayname: "&#34ee80ᴘʀɪᴄᴇ"
        lore:
          - "&fClick to type the price per item"
          - "&7(${price_each})"
      confirm:
        material: LIME_STAINED_GLASS_PANE
        displayname: "&#39FF14ᴄᴏɴꜰɪʀᴍ"
        lore:
          - "&fClick to confirm order"
          - "&7(Total: ${total})"


  select:
    title: "&#444444ᴏʀᴅᴇʀ -> Select Item"
    rows: 6
    format:
      selected_prefix: "&#34ee80• "
      unselected_prefix: "&f• "
    items:
      prev:
        slot: 45
        material: ARROW
        displayname: "&#34ee80ʙᴀᴄᴋ"
        lore:
          - "&fClick to go to the previous page"
      next:
        slot: 53
        material: ARROW
        displayname: "&#34ee80ɴᴇхᴛ"
        lore:
          - "&fClick to go to the next page"
      sort:
        slot: 48
        material: CAULDRON
        displayname: "&#34ee80ѕᴏʀᴛ"
        lore: []
      filter:
        slot: 49
        material: HOPPER
        displayname: "&#34ee80ꜰɪʟᴛᴇʀ"
        lore: []
      search:
        slot: 50
        material: OAK_SIGN
        displayname: "&#34ee80ѕᴇᴀʀᴄʜ"
        lore:
          - "&fClick to search"
      item:
        displayname: "&f{item}"
        lore:
          - "&fClick to select"


  edit:
    title: "&#444444ᴏʀᴅᴇʀѕ -> Edit Order"
    rows: 3
    filler:
      enabled: true
      slots: "0,1,2,9,11,18,19,20"
      material: GRAY_STAINED_GLASS_PANE
      displayname: "&7 "
    items:
      target:
        displayname: "&#34ee80{player}'s Order"
        lore:
          - "&f{item}"
          - "&#34ee80${price_each} &feach"
          - ""
          - "&#7E7E29{delivered}/&#008D4C{requested} &#858585Delivered"
          - "&#7E7E29${paid}/&#008D4C${total} &#858585paid"
          - ""
      cancel:
        material: RED_TERRACOTTA
        displayname: "&cᴄᴀɴᴄᴇʟ"
        lore:
          - "&fClick to cancel this order"
      collect:
        material: CHEST
        displayname: "&fᴄᴏʟʟᴇᴄᴛ"
        lore:
          - "&fClick to collect items"

  delete:
    title: "&#444444ᴏʀᴅᴇʀѕ -> Delete Order"
    rows: 3
    items:
      back:
        slot: 10
        material: RED_STAINED_GLASS_PANE
        displayname: "&#FF3B3Bʙᴀᴄᴋ"
        lore:
          - "&fClick to go back"
      confirm:
        slot: 16
        material: LIME_STAINED_GLASS_PANE
        displayname: "&#39FF14ᴄᴏɴꜰɪʀᴍ"
        lore:
          - "&fClick to delete this order!"


  collect:
    title: "&#444444ᴏʀᴅᴇʀѕ -> Collect Items"
    rows: 6
    items:
      prev:
        slot: 45
        material: ARROW
        displayname: "&#34ee80ʙᴀᴄᴋ"
        lore:
          - "&fClick to go to the previous page"
      next:
        slot: 53
        material: ARROW
        displayname: "&#34ee80ɴᴇхᴛ"
        lore:
          - "&fClick to go to the next page"
      drop:
        slot: 52
        material: DROPPER
        displayname: "&#34ee80ᴅʀᴏᴘ ʟᴏᴏᴛ"
        lore:
          - "&fClick to drop all loot on the page"
    filler:
      material: GRAY_STAINED_GLASS_PANE
      displayname: "&7 "


  deliver:
    title: "&#444444ᴏʀᴅᴇʀѕ -> Deliver Items"
    rows: 4


  confirm:
    title: "&#444444ᴏʀᴅᴇʀѕs -> Confirm Delivery"
    rows: 3
    items:
      cancel:
        material: RED_STAINED_GLASS_PANE
        displayname: "&#FF3B3Bᴄᴀɴᴄᴇʟ"
        lore: "&fClick to go back"
      summary:
        displayname: "&f{player} Order"
        lore:
          - "&#34ee80{amount} &f{item}"
          - "&#34ee80${price_each} &feach"
          - ""
          - "&7You're delivering &#34ee80{amount} &f{item}"
      confirm:
        material: LIME_STAINED_GLASS_PANE
        displayname: "&#39FF14ᴄᴏɴꜰɪʀᴍ"
        lore:
          - "&fClick to deliver items"
          - "&7({receive})"
